version: '3.8'

services:
  nodejs:
    image: node:18-alpine
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - 3000:3000
    command: ["tail", "-f", "/dev/null"]

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./build:/usr/share/nginx/html
    ports:
      - 8000:80
    command: ["nginx", "-g", "daemon off;"]
